//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LI_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplication
    {
        public int ApplicationID { get; set; }
        public Nullable<System.DateTime> DateOfApplication { get; set; }
        public string CauseForApplication { get; set; }
        public string EmployerFirm { get; set; }
        public Nullable<bool> Emergency { get; set; }
        public string ApplicationStatus { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
